/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.GestionDeCarreras;
import Modelo.CorredorCarrera;
import cronometro.CronometroListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Mario
 */
public class CorrerCarrera extends javax.swing.JDialog {

    private GestionDeCarreras gdCarreras;
    private int idCarrera;

    /**
     * Creates new form CorrerCarrera
     */
    public CorrerCarrera(java.awt.Dialog parent, boolean modal, GestionDeCarreras gdCarreras, int idCarrera) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.gdCarreras = gdCarreras;
        this.idCarrera = idCarrera;

        cronometro.setListadorsales(gdCarreras.listaDorsales(idCarrera));
        cronometro.setCronometroListener(new CronometroListener() {
            @Override
            public void resgistrarTiempo(int dorsal, String tiempo, boolean finalizar) {
                if (finalizar) {
                    acabarCarrera();
                } else {
                    System.out.println("hola " + dorsal + " " + tiempo);
                    gdCarreras.getListaCarreras().get(idCarrera)
                            .getListaCorredores().get(dorsal - 1).setTiempoCarrera(tiempo);
                    cargarDorsales();
                }
            }
        });
        cronometro.start();

    }

    public void cargarDorsales() {
        cronometro.setListadorsales(gdCarreras.listaDorsales(idCarrera));
    }

    public void acabarCarrera() {
        gdCarreras.getListaCarreras().get(idCarrera).finCarrera();
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCorrer = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        cronometro = new cronometro.Cronometro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cronometro.setText("cronometro1");

        javax.swing.GroupLayout jPanelCorrerLayout = new javax.swing.GroupLayout(jPanelCorrer);
        jPanelCorrer.setLayout(jPanelCorrerLayout);
        jPanelCorrerLayout.setHorizontalGroup(
            jPanelCorrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCorrerLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCorrerLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanelCorrerLayout.setVerticalGroup(
            jPanelCorrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCorrerLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCorrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCorrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<Integer> listaDorsales = gdCarreras.listaDorsales(idCarrera);
        System.out.println("SIZE " + listaDorsales.size());
        for (Integer dorsale : listaDorsales) {
            System.out.println(dorsale);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cronometro.Cronometro cronometro;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanelCorrer;
    // End of variables declaration//GEN-END:variables
}
