/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.GestionDeCarreras;
import Modelo.CorredorCarrera;
import cronometro.CronometroListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Mario
 */
public class CorrerCarrera extends javax.swing.JDialog {

    private GestionDeCarreras gdCarreras;
    private int idCarrera, posicion = 1;

    /**
     * Creates new form CorrerCarrera
     */
    public CorrerCarrera(java.awt.Dialog parent, boolean modal, GestionDeCarreras gdCarreras, int idCarrera) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.gdCarreras = gdCarreras;
        this.idCarrera = idCarrera;
        jLabelNomCarrera.setText(gdCarreras.getListaCarreras().get(idCarrera).getNombre());
        cronometro.setListadorsales(gdCarreras.listaDorsales(idCarrera));
        cronometro.setCronometroListener(new CronometroListener() {
            @Override
            public void resgistrarTiempo(int dorsal, String tiempo, boolean finalizar) {
                if (finalizar) {
                    acabarCarrera();
                } else {
                    gdCarreras.buscarPorDorsal(idCarrera, dorsal, tiempo, posicion);
                    /*gdCarreras.getListaCarreras().get(idCarrera)
                    .getListaCorredores().get(dorsal - 1).setTiempoCarrera(tiempo);
                    gdCarreras.getListaCarreras().get(idCarrera)
                    .getListaCorredores().get(dorsal - 1).setPosicion(posicion);*/
                    posicion++;
                    cargarDorsales();
                }
            }
        });
        cronometro.start();

    }

    public void cargarDorsales() {
        cronometro.setListadorsales(gdCarreras.listaDorsales(idCarrera));
    }

    public void acabarCarrera() {
        gdCarreras.getListaCarreras().get(idCarrera).finCarrera();
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCorrer = new javax.swing.JPanel();
        cronometro = new cronometro.Cronometro();
        jButtonTerminar = new javax.swing.JButton();
        jLabelNomCarrera = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cronometro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cronometro.setText("cronometro1");

        jButtonTerminar.setText("Terminar carrera");
        jButtonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminarActionPerformed(evt);
            }
        });

        jLabelNomCarrera.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabelNomCarrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomCarrera.setText("jLabel1");

        javax.swing.GroupLayout jPanelCorrerLayout = new javax.swing.GroupLayout(jPanelCorrer);
        jPanelCorrer.setLayout(jPanelCorrerLayout);
        jPanelCorrerLayout.setHorizontalGroup(
            jPanelCorrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCorrerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCorrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cronometro, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(jButtonTerminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNomCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCorrerLayout.setVerticalGroup(
            jPanelCorrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCorrerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomCarrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jButtonTerminar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCorrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCorrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerminarActionPerformed
        acabarCarrera();
    }//GEN-LAST:event_jButtonTerminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cronometro.Cronometro cronometro;
    private javax.swing.JButton jButtonTerminar;
    private javax.swing.JLabel jLabelNomCarrera;
    private javax.swing.JPanel jPanelCorrer;
    // End of variables declaration//GEN-END:variables
}
