/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.GestionDeCarreras;
import Modelo.CorredorCarrera;
import cronometro.CronometroListener;
import java.util.List;

/**
 *
 * @author Mario
 */
public class CorrerCarrera extends javax.swing.JDialog {

    private GestionDeCarreras gdCarreras;
    private int idCarrera;

    /**
     * Creates new form CorrerCarrera
     */
    public CorrerCarrera(java.awt.Dialog parent, boolean modal, GestionDeCarreras gdCarreras, int idCarrera) {
        super(parent, modal);
        initComponents();

        this.gdCarreras = gdCarreras;
        this.idCarrera = idCarrera;

        cronometro.setListadorsales(gdCarreras.listaDorsales(idCarrera));
        cronometro.setCronometroListener(new CronometroListener() {
            @Override
            public void resgistrarTiempo(int dorsal, String tiempo) {

                System.out.println("hola " + dorsal + " " + tiempo);
                cargarDorsales();
            }
        });

    }

    public void cargarDorsales() {
        cronometro.setListadorsales(gdCarreras.listaDorsales(idCarrera));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCorrer = new javax.swing.JPanel();
        cronometro = new cronometro.Cronometro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cronometro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cronometro.setText("cronometro1");

        javax.swing.GroupLayout jPanelCorrerLayout = new javax.swing.GroupLayout(jPanelCorrer);
        jPanelCorrer.setLayout(jPanelCorrerLayout);
        jPanelCorrerLayout.setHorizontalGroup(
            jPanelCorrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCorrerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cronometro, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCorrerLayout.setVerticalGroup(
            jPanelCorrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCorrerLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCorrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCorrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cronometro.Cronometro cronometro;
    private javax.swing.JPanel jPanelCorrer;
    // End of variables declaration//GEN-END:variables
}
