/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.GestionArchivosCSV;
import Logica.GestionDeCarreras;
import Logica.GestionDeCorredores;
import Logica.GestionFicherosObjetos;
import Logica.SingletonGestionCarreras;
import Logica.SingletonGestionCorredores;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.text.ParseException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import org.openide.util.Exceptions;

/**
 *
 * @author alumnop
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private GestionDeCorredores gdCorredores;
    private GestionDeCarreras gdCarreras;
    private GestionArchivosCSV gacsv;
    private GestionFicherosObjetos gfO;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            //UIManager.setLookAndFeel(com.jtattoo.plaf.smart.SmartLookAndFeel.class.getCanonicalName());
            //SwingUtilities.updateComponentTreeUI(this.getParent());
            //SwingUtilities.updateComponentTreeUI(this);
        } catch (Throwable e) {
            e.printStackTrace();
        }
        gdCorredores = SingletonGestionCorredores.getInstance();
        gdCarreras = SingletonGestionCarreras.getInstance();
        gacsv = new GestionArchivosCSV();
        ponLaAyuda();
        File tempCsv = new File("corredores.txt");
        if (tempCsv.exists()) {
            try {
                gdCorredores.importarCorredores(gacsv.leerFichero("corredores.txt"));
            } catch (ParseException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            gacsv.abrirFicheroEscritura("corredores.txt", false);
            gacsv.cerrarFicheroEscritura();
        }

        File tempFichero = new File("carreras.dat");
        gfO = new GestionFicherosObjetos();

        if (tempFichero.exists()) {
            gfO.abrirFicheroLecturaObjetos("carreras.dat");
            try {
                GestionDeCarreras carrerasImportadas = gfO.leerUnRegistroFicheroObjetos();
                gdCarreras.importarCarreras(carrerasImportadas.getListaCarreras());
                gfO.cerrarFicherosLecturaObjetos();
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            } catch (ClassNotFoundException ex) {
                Exceptions.printStackTrace(ex);
            }
        } else {
            gfO.abrirFicheroEscrituraObjetos("carreras.dat");
            gfO.grabarObjetoFicheroObjetos(gdCarreras);
            gfO.cerrarFicherosEscrituraObjetos();
        }

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                super.windowClosing(we);
                gfO.abrirFicheroEscrituraObjetos("carreras.dat");
                gfO.grabarObjetoFicheroObjetos(gdCarreras);
                gfO.cerrarFicherosEscrituraObjetos();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCorredor = new javax.swing.JPanel();
        jLabelCorredores = new javax.swing.JLabel();
        jButtonAlta = new javax.swing.JButton();
        jButtonListadoCoredores = new javax.swing.JButton();
        jPanelCarreras = new javax.swing.JPanel();
        jLabelCarreras = new javax.swing.JLabel();
        jButtonAltaCarrera = new javax.swing.JButton();
        jButtonListadoCarrera = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonConf = new javax.swing.JButton();
        jButtonHelp = new javax.swing.JButton();
        jButtonInformes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCorredores.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabelCorredores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCorredores.setText("Corredores");

        jButtonAlta.setText("Alta de corredores");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonListadoCoredores.setText("Listado de corredores");
        jButtonListadoCoredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListadoCoredoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCorredorLayout = new javax.swing.GroupLayout(jPanelCorredor);
        jPanelCorredor.setLayout(jPanelCorredorLayout);
        jPanelCorredorLayout.setHorizontalGroup(
            jPanelCorredorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCorredorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCorredorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCorredores, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addComponent(jButtonAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonListadoCoredores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCorredorLayout.setVerticalGroup(
            jPanelCorredorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCorredorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCorredores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonListadoCoredores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelCarreras.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabelCarreras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCarreras.setText("Carreras");

        jButtonAltaCarrera.setText("Alta de carreras");
        jButtonAltaCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaCarreraActionPerformed(evt);
            }
        });

        jButtonListadoCarrera.setText("Listado de carreras");
        jButtonListadoCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListadoCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCarrerasLayout = new javax.swing.GroupLayout(jPanelCarreras);
        jPanelCarreras.setLayout(jPanelCarrerasLayout);
        jPanelCarrerasLayout.setHorizontalGroup(
            jPanelCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarrerasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCarreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAltaCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonListadoCarrera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCarrerasLayout.setVerticalGroup(
            jPanelCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarrerasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCarreras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAltaCarrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonListadoCarrera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonConf.setText("Configuración");
        jButtonConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfActionPerformed(evt);
            }
        });

        jButtonHelp.setText("Ayuda");

        jButtonInformes.setText("Informes");
        jButtonInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConf, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addComponent(jButtonHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonInformes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonConf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInformes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCarreras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCorredor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCorredor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCarreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        AltaCorredor altacorredor = new AltaCorredor(this, true, gdCorredores, gacsv);
        altacorredor.setVisible(true);
        gacsv.abrirFicheroEscritura("corredores.txt", false);
        try {
            gacsv.escribirCadena(gdCorredores.cadenaCsv());
        } catch (IOException ex) {
            Logger.getLogger(ListadoCorredor.class.getName()).log(Level.SEVERE, null, ex);
        }
        gacsv.cerrarFicheroEscritura();
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jButtonListadoCoredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListadoCoredoresActionPerformed
        ListadoCorredor listadoCorredor = null;
        listadoCorredor = new ListadoCorredor(this, true, gdCorredores, gacsv);
        listadoCorredor.setVisible(true);
    }//GEN-LAST:event_jButtonListadoCoredoresActionPerformed

    private void jButtonAltaCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaCarreraActionPerformed
        AltaCarrera altaCarrera = new AltaCarrera(this, true, gdCarreras);
        altaCarrera.setVisible(true);
        gfO.abrirFicheroEscrituraObjetos("carreras.dat");
        gfO.grabarObjetoFicheroObjetos(gdCarreras);
        gfO.cerrarFicherosEscrituraObjetos();
    }//GEN-LAST:event_jButtonAltaCarreraActionPerformed

    private void jButtonListadoCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListadoCarreraActionPerformed
        ListadoCarrera listadoCarrera = new ListadoCarrera(this, true, gdCarreras, gdCorredores);
        listadoCarrera.setVisible(true);
        /*gfO.abrirFicheroEscrituraObjetos("carreras.dat");
        gfO.grabarObjetoFicheroObjetos(gdCarreras);
        gfO.cerrarFicherosEscrituraObjetos();*/
    }//GEN-LAST:event_jButtonListadoCarreraActionPerformed

    private void jButtonConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfActionPerformed
        Configuracion conf = new Configuracion(this, true, gdCarreras);
        conf.setVisible(true);
    }//GEN-LAST:event_jButtonConfActionPerformed

    private void jButtonInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformesActionPerformed
        Informes informes = new Informes(this, true, gdCarreras, gdCorredores);
        informes.setVisible(true);
    }//GEN-LAST:event_jButtonInformesActionPerformed

    private void ponLaAyuda() {
        try {
            // Carga el fichero de ayuda
            File fichero = new File("help" + File.separator + "help_set.hs");
            URL hsURL = fichero.toURI().toURL();

            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            hb.enableHelpOnButton(jButtonHelp, "aplicacion", helpset);

            hb.enableHelpKey(getRootPane(), "aplicacion", helpset);
            hb.enableHelpKey(jButtonAlta,"alta_corredor",helpset);
            hb.enableHelpKey(jButtonListadoCoredores,"lista_corredor",helpset);
            hb.enableHelpKey(jButtonAltaCarrera,"alta_carrera",helpset);
            hb.enableHelpKey(jButtonListadoCarrera,"lista_carrera",helpset);
            hb.enableHelpKey(jButtonConf,"configuracion",helpset);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Locale.setDefault(new Locale("es", "ES"));
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonAltaCarrera;
    private javax.swing.JButton jButtonConf;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonInformes;
    private javax.swing.JButton jButtonListadoCarrera;
    private javax.swing.JButton jButtonListadoCoredores;
    private javax.swing.JLabel jLabelCarreras;
    private javax.swing.JLabel jLabelCorredores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCarreras;
    private javax.swing.JPanel jPanelCorredor;
    // End of variables declaration//GEN-END:variables
}
